//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifySms // you might wanna change that name 
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractSingleMessageRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.AbstractSingleEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.AbstractSingleVoiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleVoiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleVoiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.AbstractSingleSmsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleSmsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleSmsRequest))]
    public partial class AbstractSingleMessageRequest : object
    {
        
        private System.Guid ApplicationIDField;
        
        private System.Nullable<System.DateTime> FutureSendDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FutureSendDate
        {
            get
            {
                return this.FutureSendDateField;
            }
            set
            {
                this.FutureSendDateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractSingleEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleEmailRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleEmailRequest))]
    public partial class AbstractSingleEmailRequest : NotifySms.AbstractSingleMessageRequest
    {
        
        private string MailMessageTextField;
        
        private string MailSenderNameField;
        
        private string ReplyToEmailAddressField;
        
        private string ReplyToMailAddressField;
        
        private string SubjectMailTextField;
        
        private string TagNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailMessageText
        {
            get
            {
                return this.MailMessageTextField;
            }
            set
            {
                this.MailMessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MailSenderName
        {
            get
            {
                return this.MailSenderNameField;
            }
            set
            {
                this.MailSenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReplyToEmailAddress
        {
            get
            {
                return this.ReplyToEmailAddressField;
            }
            set
            {
                this.ReplyToEmailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReplyToMailAddress
        {
            get
            {
                return this.ReplyToMailAddressField;
            }
            set
            {
                this.ReplyToMailAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectMailText
        {
            get
            {
                return this.SubjectMailTextField;
            }
            set
            {
                this.SubjectMailTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName
        {
            get
            {
                return this.TagNameField;
            }
            set
            {
                this.TagNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleEmailRequest : NotifySms.AbstractSingleEmailRequest
    {
        
        private string RecipientMailAddressField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecipientMailAddress
        {
            get
            {
                return this.RecipientMailAddressField;
            }
            set
            {
                this.RecipientMailAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdpSingleEmailRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class IdpSingleEmailRequest : NotifySms.AbstractSingleEmailRequest
    {
        
        private string IdentityNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber
        {
            get
            {
                return this.IdentityNumberField;
            }
            set
            {
                this.IdentityNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractSingleVoiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleVoiceRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleVoiceRequest))]
    public partial class AbstractSingleVoiceRequest : NotifySms.AbstractSingleMessageRequest
    {
        
        private System.Nullable<NotifySms.MessageLanguage> ForceLanguageField;
        
        private System.Nullable<NotifySms.VoiceMessageMaxSendRetryCount> MaxSendRetryCountField;
        
        private string MessageTextField;
        
        private System.Nullable<NotifySms.VoiceMessageSendRetryInterval> SendRetryIntervalField;
        
        private string SenderNumberField;
        
        private string TagNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<NotifySms.MessageLanguage> ForceLanguage
        {
            get
            {
                return this.ForceLanguageField;
            }
            set
            {
                this.ForceLanguageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<NotifySms.VoiceMessageMaxSendRetryCount> MaxSendRetryCount
        {
            get
            {
                return this.MaxSendRetryCountField;
            }
            set
            {
                this.MaxSendRetryCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageText
        {
            get
            {
                return this.MessageTextField;
            }
            set
            {
                this.MessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<NotifySms.VoiceMessageSendRetryInterval> SendRetryInterval
        {
            get
            {
                return this.SendRetryIntervalField;
            }
            set
            {
                this.SendRetryIntervalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderNumber
        {
            get
            {
                return this.SenderNumberField;
            }
            set
            {
                this.SenderNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName
        {
            get
            {
                return this.TagNameField;
            }
            set
            {
                this.TagNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleVoiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleVoiceRequest : NotifySms.AbstractSingleVoiceRequest
    {
        
        private string RecipientNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RecipientNumber
        {
            get
            {
                return this.RecipientNumberField;
            }
            set
            {
                this.RecipientNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdpSingleVoiceRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class IdpSingleVoiceRequest : NotifySms.AbstractSingleVoiceRequest
    {
        
        private string IdentityNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber
        {
            get
            {
                return this.IdentityNumberField;
            }
            set
            {
                this.IdentityNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AbstractSingleSmsRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleSmsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.IdpSingleSmsRequest))]
    public partial class AbstractSingleSmsRequest : NotifySms.AbstractSingleMessageRequest
    {
        
        private string GroupNumberField;
        
        private string SmsMessageTextField;
        
        private string SmsSenderNameField;
        
        private string TagNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupNumber
        {
            get
            {
                return this.GroupNumberField;
            }
            set
            {
                this.GroupNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsMessageText
        {
            get
            {
                return this.SmsMessageTextField;
            }
            set
            {
                this.SmsMessageTextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SmsSenderName
        {
            get
            {
                return this.SmsSenderNameField;
            }
            set
            {
                this.SmsSenderNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TagName
        {
            get
            {
                return this.TagNameField;
            }
            set
            {
                this.TagNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleSmsRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleSmsRequest : NotifySms.AbstractSingleSmsRequest
    {
        
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber
        {
            get
            {
                return this.PhoneNumberField;
            }
            set
            {
                this.PhoneNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdpSingleSmsRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class IdpSingleSmsRequest : NotifySms.AbstractSingleSmsRequest
    {
        
        private string IdentityNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentityNumber
        {
            get
            {
                return this.IdentityNumberField;
            }
            set
            {
                this.IdentityNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageLanguage", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public enum MessageLanguage : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hebrew = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Arabic = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        English = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Russian = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoiceMessageMaxSendRetryCount", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public enum VoiceMessageMaxSendRetryCount : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoRetry0 = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Once1 = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Twice2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThreeTimes3 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FourTimes4 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FiveTimes5 = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VoiceMessageSendRetryInterval", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public enum VoiceMessageSendRetryInterval : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TwoMinutes2 = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FiveMinutes5 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TenMinutes10 = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FifteenMinutes15 = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThirtyMinutes30 = 30,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleEmailResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(NotifySms.SingleSmsResponse))]
    public partial class SingleMessageResponse : object
    {
        
        private System.Guid MessageIDField;
        
        private NotifySms.MessageStatus StatusField;
        
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.MessageStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleEmailResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleEmailResponse : NotifySms.SingleMessageResponse
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleSmsResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleSmsResponse : NotifySms.SingleMessageResponse
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notifier.Schema.Message")]
    public enum MessageStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Initial = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationNotExists = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ThisMessageTypeNotAllowedForEntity = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedByQuota = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FailedByParentQuota = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ApplicationIdDeleted = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactProvidedByIdpService = 1000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IdpServiceCallError = 1001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ContactNotProvidedByIdpService = 1100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageRegisteredAsFallBack = 400,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageScheduled = 500,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduleMessagesExpired = 501,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PastSendDateError = 510,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledMessageTimeSlotFullError = 520,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledMessageCanceledByCustomer = 530,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ScheduledMessageInProcess = 550,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSent = 2000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsProviderServiceCallError = 2001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifierSmsError_ID = 2003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifierSmsError_Quota = 2004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifierSmsError_Blocked = 2005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NotifierSmsError_UserIDError = 2006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SentByParentQuota = 2010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyPhoneNumber = 2020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptySmsMessageText = 2030,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongFormat_FutureSendDate = 2040,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongFormat_PhoneNumber = 2050,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongFormat_SmsSenderNumber = 2060,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongFormat_SmsSenderName = 2070,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongPhoneNumberPrefix = 2080,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsSenderNameNotAllowed = 2090,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GeneralSmsProviderError = 2100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KosherRecipientPhoneNumber = 2300,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsRecievedByRecipient = 2900,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SmsNotRecievedByRecipient = 2910,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailSent = 3000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmptyRecipientEmailAddress = 3010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WrongFormat_RecipientEmailAddress = 3020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailProviderCallError = 3001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailNotReceivedBadRecipentAddress = 3030,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailNotReceivedMailboxFull = 3040,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailNotReceivedRejectedByRemoteServer = 3050,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailNotRecieved = 3060,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailReplyToAddressNotAllowed = 3090,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EmailReceived = 3900,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageSuccess = 4000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageErrorGeneratedByVoiceProvider = 4001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageExceptionInTheCallToVoiceProviderAPI = 4002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageGeneralErrorInVoiceMessageService = 4003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessage401UnauthorizedError = 4004,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageTheResultsParsingIsFailed = 4005,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageMessageNotDelivered = 4006,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageUnexpectedOutputFromPaycallApi = 4007,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageInvalidInput = 4008,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageInvalidPhoneNumber = 4009,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageClientInvalidInput = 4010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageClientSendInternalError = 4011,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageClientInternalErrorInGetStatus = 4012,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageClientInvalidphoneNumber = 4020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageSenderNumberNotAllowed = 4090,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageGeneralProviderError = 4100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageInternalErrorInGetStatus = 4103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageStatusTheResultsParsingIsFailed = 4105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageRecievedByRecipient = 4900,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VoiceMessageNotRecievedByRecipient = 4910,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageDelivered = 5000,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CustomerWebHookCallError = 5001,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageNotDelivered = 5010,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageNotSent = 5020,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 5002,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MessageSent_DeliveryNotificationApiUnavailable = 5003,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AskedAboutStatus = 5030,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleVoiceResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleVoiceResponse : object
    {
        
        private string DescriptionField;
        
        private System.Guid MessageIDField;
        
        private int ResultCodeField;
        
        private NotifySms.MessageStatus StatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ResultCode
        {
            get
            {
                return this.ResultCodeField;
            }
            set
            {
                this.ResultCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.MessageStatus Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelMessagesRequest", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class CancelMessagesRequest : object
    {
        
        private System.Guid ApplicationIDField;
        
        private System.Guid[] MessagesIDsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ApplicationID
        {
            get
            {
                return this.ApplicationIDField;
            }
            set
            {
                this.ApplicationIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid[] MessagesIDs
        {
            get
            {
                return this.MessagesIDsField;
            }
            set
            {
                this.MessagesIDsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CancelMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class CancelMessageResponse : object
    {
        
        private NotifySms.SingleCancelMessageResponse[] ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.SingleCancelMessageResponse[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SingleCancelMessageResponse", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class SingleCancelMessageResponse : object
    {
        
        private bool IsCancelDoneNowField;
        
        private System.Guid MessageIDField;
        
        private System.Nullable<NotifySms.MessageStatus> StatusField;
        
        private string StatusDescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCancelDoneNow
        {
            get
            {
                return this.IsCancelDoneNowField;
            }
            set
            {
                this.IsCancelDoneNowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid MessageID
        {
            get
            {
                return this.MessageIDField;
            }
            set
            {
                this.MessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<NotifySms.MessageStatus> Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusDescription
        {
            get
            {
                return this.StatusDescriptionField;
            }
            set
            {
                this.StatusDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DualOptionMessageSettings", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class DualOptionMessageSettings : object
    {
        
        private NotifySms.FallbackAction ActionAfterAsyncWaitField;
        
        private int MinutesToAsyncWaitForPrimaryMesageDeliveryStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.FallbackAction ActionAfterAsyncWait
        {
            get
            {
                return this.ActionAfterAsyncWaitField;
            }
            set
            {
                this.ActionAfterAsyncWaitField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MinutesToAsyncWaitForPrimaryMesageDeliveryStatus
        {
            get
            {
                return this.MinutesToAsyncWaitForPrimaryMesageDeliveryStatusField;
            }
            set
            {
                this.MinutesToAsyncWaitForPrimaryMesageDeliveryStatusField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FallbackAction", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public enum FallbackAction : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SendFallback = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CancelFallback = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DualOptionMessageState", Namespace="http://schemas.datacontract.org/2004/07/Mz.Notify.Customer.Schema")]
    public partial class DualOptionMessageState : object
    {
        
        private System.Guid DualOptionMessageIDField;
        
        private int DualStateField;
        
        private string DualStateDescriptionField;
        
        private System.Guid FallbackMessageIDField;
        
        private NotifySms.MessageStatus FallbackMessageStatusField;
        
        private System.DateTime FallbackMessageStatusLastModifiedField;
        
        private System.Guid PrimaryMessageIDField;
        
        private NotifySms.MessageStatus PrimaryMessageStatusField;
        
        private System.DateTime PrimaryMessageStatusLastModifiedField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid DualOptionMessageID
        {
            get
            {
                return this.DualOptionMessageIDField;
            }
            set
            {
                this.DualOptionMessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DualState
        {
            get
            {
                return this.DualStateField;
            }
            set
            {
                this.DualStateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DualStateDescription
        {
            get
            {
                return this.DualStateDescriptionField;
            }
            set
            {
                this.DualStateDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid FallbackMessageID
        {
            get
            {
                return this.FallbackMessageIDField;
            }
            set
            {
                this.FallbackMessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.MessageStatus FallbackMessageStatus
        {
            get
            {
                return this.FallbackMessageStatusField;
            }
            set
            {
                this.FallbackMessageStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FallbackMessageStatusLastModified
        {
            get
            {
                return this.FallbackMessageStatusLastModifiedField;
            }
            set
            {
                this.FallbackMessageStatusLastModifiedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid PrimaryMessageID
        {
            get
            {
                return this.PrimaryMessageIDField;
            }
            set
            {
                this.PrimaryMessageIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotifySms.MessageStatus PrimaryMessageStatus
        {
            get
            {
                return this.PrimaryMessageStatusField;
            }
            set
            {
                this.PrimaryMessageStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PrimaryMessageStatusLastModified
        {
            get
            {
                return this.PrimaryMessageStatusLastModifiedField;
            }
            set
            {
                this.PrimaryMessageStatusLastModifiedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.INotifyApiService")]
    public interface INotifyApiService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyApiService/SendSingleSmsMessage", ReplyAction="http://tempuri.org/INotifyApiService/SendSingleSmsMessageResponse")]
        System.Threading.Tasks.Task<NotifySms.SingleSmsResponse> SendSingleSmsMessageAsync(NotifySms.AbstractSingleSmsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyApiService/SendSingleEmailMessage", ReplyAction="http://tempuri.org/INotifyApiService/SendSingleEmailMessageResponse")]
        System.Threading.Tasks.Task<NotifySms.SingleEmailResponse> SendSingleEmailMessageAsync(NotifySms.AbstractSingleEmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyApiService/SendSingleVoiceMessage", ReplyAction="http://tempuri.org/INotifyApiService/SendSingleVoiceMessageResponse")]
        System.Threading.Tasks.Task<NotifySms.SingleVoiceResponse> SendSingleVoiceMessageAsync(NotifySms.AbstractSingleVoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyApiService/CancelMessages", ReplyAction="http://tempuri.org/INotifyApiService/CancelMessagesResponse")]
        System.Threading.Tasks.Task<NotifySms.CancelMessageResponse> CancelMessagesAsync(NotifySms.CancelMessagesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotifyApiService/SendDualOptionMessage", ReplyAction="http://tempuri.org/INotifyApiService/SendDualOptionMessageResponse")]
        System.Threading.Tasks.Task<NotifySms.DualOptionMessageState> SendDualOptionMessageAsync(NotifySms.AbstractSingleMessageRequest primaryMessage, NotifySms.AbstractSingleMessageRequest fallbackMessage, NotifySms.DualOptionMessageSettings settings);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface INotifyApiServiceChannel : NotifySms.INotifyApiService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class NotifyApiServiceClient : System.ServiceModel.ClientBase<NotifySms.INotifyApiService>, NotifySms.INotifyApiService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NotifyApiServiceClient() : 
                base(NotifyApiServiceClient.GetDefaultBinding(), NotifyApiServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_INotifyApiService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotifyApiServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(NotifyApiServiceClient.GetBindingForEndpoint(endpointConfiguration), NotifyApiServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotifyApiServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NotifyApiServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotifyApiServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NotifyApiServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NotifyApiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<NotifySms.SingleSmsResponse> SendSingleSmsMessageAsync(NotifySms.AbstractSingleSmsRequest request)
        {
            return base.Channel.SendSingleSmsMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotifySms.SingleEmailResponse> SendSingleEmailMessageAsync(NotifySms.AbstractSingleEmailRequest request)
        {
            return base.Channel.SendSingleEmailMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotifySms.SingleVoiceResponse> SendSingleVoiceMessageAsync(NotifySms.AbstractSingleVoiceRequest request)
        {
            return base.Channel.SendSingleVoiceMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotifySms.CancelMessageResponse> CancelMessagesAsync(NotifySms.CancelMessagesRequest request)
        {
            return base.Channel.CancelMessagesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NotifySms.DualOptionMessageState> SendDualOptionMessageAsync(NotifySms.AbstractSingleMessageRequest primaryMessage, NotifySms.AbstractSingleMessageRequest fallbackMessage, NotifySms.DualOptionMessageSettings settings)
        {
            return base.Channel.SendDualOptionMessageAsync(primaryMessage, fallbackMessage, settings);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotifyApiService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_INotifyApiService))
            {
                return new System.ServiceModel.EndpointAddress("http://devtest.comda.co.il:8099/NotifyApiService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return NotifyApiServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_INotifyApiService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return NotifyApiServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_INotifyApiService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_INotifyApiService,
        }
    }
}
