export interface ICountry {
    Description: string;
    Code: string;
}

const Countries: ICountry[] = [
    { Description: "Andorra", Code: "AD" },
    { Description: "United Arab Emirates", Code: "AE" },
    { Description: "Afghanistan", Code: "AF" },
    { Description: "Antigua and Barbuda", Code: "AG" },
    { Description: "Anguilla", Code: "AI" },
    { Description: "Albania", Code: "AL" },
    { Description: "Armenia", Code: "AM" },
    { Description: "Netherlands Antilles", Code: "AN" },
    { Description: "Angola", Code: "AO" },
    { Description: "Antarctica", Code: "AQ" },
    { Description: "Argentina", Code: "AR" },
    { Description: "AmericanSamoa", Code: "AS" },
    { Description: "Austria", Code: "AT" },
    { Description: "Australia", Code: "AU" },
    { Description: "Aruba", Code: "AW" },
    { Description: "Aland Islands", Code: "AX" },
    { Description: "Azerbaijan", Code: "AZ" },
    { Description: "Bosnia and Herzegovina", Code: "BA" },
    { Description: "Barbados", Code: "BB" },
    { Description: "Bangladesh", Code: "BD" },
    { Description: "Belgium", Code: "BE" },
    { Description: "Burkina Faso", Code: "BF" },
    { Description: "Bulgaria", Code: "BG" },
    { Description: "Bahrain", Code: "BH" },
    { Description: "Burundi", Code: "BI" },
    { Description: "Benin", Code: "BJ" },
    { Description: "Saint Barthelemy", Code: "BL" },
    { Description: "Bermuda", Code: "BM" },
    { Description: "Brunei Darussalam", Code: "BN" },
    { Description: "Bermuda", Code: "BM" },
    { Description: "Bolivia, Plurinational State of", Code: "BO" },
    { Description: "Brazil", Code: "BR" },
    { Description: "Bahamas", Code: "BS" },
    { Description: "Bhutan", Code: "BT" },
    { Description: "Botswana", Code: "BW" },
    { Description: "Belarus", Code: "BY" },
    { Description: "Belize", Code: "BZ" },
    { Description: "Canada", Code: "CA" },
    { Description: "Cocos (Keeling) Islands", Code: "CC" },
    { Description: "Congo, The Democratic Republic of the Congo", Code: "CD" },
    { Description: "Central African Republic", Code: "CF" },
    { Description: "Congo", Code: "CG" },
    { Description: "Switzerland", Code: "CH" },
    { Description: "Cote d'Ivoire", Code: "CI" },
    { Description: "Cook Islands", Code: "CK" },
    { Description: "Chile", Code: "CL" },
    { Description: "Cameroon", Code: "CM" },
    { Description: "China", Code: "CN" },
    { Description: "Colombia", Code: "CO" },
    { Description: "Costa Rica", Code: "CR" },
    { Description: "Cuba", Code: "CU" },
    { Description: "Cape Verde", Code: "CV" },
    { Description: "Christmas Island", Code: "CX" },
    { Description: "Cyprus", Code: "CY" },
    { Description: "Czech Republic", Code: "CZ" },
    { Description: "Germany", Code: "DE" },
    { Description: "Djibouti", Code: "DJ" },
    { Description: "Denmark", Code: "DK" },
    { Description: "Dominica", Code: "DM" },
    { Description: "Dominican Republic", Code: "DO" },
    { Description: "Algeria", Code: "DZ" },
    { Description: "Ecuador", Code: "EC" },
    { Description: "Estonia", Code: "EE" },
    { Description: "Egypt", Code: "EG" },
    { Description: "Eritrea", Code: "ER" },
    { Description: "Spain", Code: "ES" },
    { Description: "Ethiopia", Code: "ET" },
    { Description: "Finland", Code: "FI" },
    { Description: "Fiji", Code: "FI" },
    { Description: "Falkland Islands (Malvinas)", Code: "FK" },
    { Description: "Micronesia, Federated States of Micronesia", Code: "FM" },
    { Description: "Faroe Islands", Code: "FO" },
    { Description: "France", Code: "FR" },
    { Description: "Gabon", Code: "GA" },
    { Description: "United Kingdom", Code: "GB" },
    { Description: "Grenada", Code: "GD" },
    { Description: "Georgia", Code: "GE" },
    { Description: "French Guiana", Code: "GF" },
    { Description: "Guernsey", Code: "GG" },
    { Description: "Ghana", Code: "GH" },
    { Description: "Gibraltar", Code: "GI" },
    { Description: "Greenland", Code: "GL" },
    { Description: "Gambia", Code: "Gambia" },
    { Description: "Guinea", Code: "GN" },
    { Description: "Guadeloupe", Code: "GP" },
    { Description: "Equatorial Guinea", Code: "GQ" },
    { Description: "South Georgia and the South Sandwich Islands", Code: "GS" },
    { Description: "Guatemala", Code: "GT" },
    { Description: "Guam", Code: "GU" },
    { Description: "Guinea-Bissau", Code: "GW" },
    { Description: "Guyana", Code: "GY" },
    { Description: "Hong Kong", Code: "HK" },
    { Description: "Honduras", Code: "HN" },
    { Description: "Croatia", Code: "HR" },
    { Description: "Haiti", Code: "HT" },
    { Description: "Hungary", Code: "HU" },
    { Description: "Indonesia", Code: "ID" },
    { Description: "Israel", Code: "IL" },
    { Description: "Isle of Man", Code: "IM" },
    { Description: "India", Code: "IN" },
    { Description: "British Indian Ocean Territory", Code: "IO" },
    { Description: "Iraq", Code: "IQ" },
    { Description: "Iran, Islamic Republic of Persian Gulf", Code: "IR" },
    { Description: "Iceland", Code: "IS" },
    { Description: "Italy", Code: "IT" },
    { Description: "Jersey", Code: "JE" },
    { Description: "Jamaica", Code: "JM" },
    { Description: "Jordan", Code: "JO" },
    { Description: "Japan", Code: "JP" },
    { Description: "Kenya", Code: "KE" },
    { Description: "Kyrgyzstan", Code: "KG" },
    { Description: "Cambodia", Code: "KI" },
    { Description: "Kiribati", Code: "KM" },
    { Description: "Saint Kitts and Nevis", Code: "KN" },
    { Description: "Korea, Democratic People's Republic of Korea", Code: "KP"},
    { Description: "Korea, Republic of South Korea", Code: "KR" },
    { Description: "Kuwait", Code: "KW" },
    { Description: "Cayman Islands", Code: "KY" },
    { Description: "Kazakhstan", Code: "KZ" },
    { Code: "LA", Description: "Laos" },
    { Code: "LB", Description: "Lebanon" },
    { Code: "LC", Description: "Saint Lucia" },
    { Code: "LI", Description: "Liechtenstein" },
    { Code: "LK", Description: "Sri Lanka" },
    { Code: "LR", Description: "Liberia" },
    { Code: "LS", Description: "Lesotho" },
    { Code: "LT", Description: "Lithuania" },
    { Code: "LU", Description: "Luxembourg" },
    { Code: "LV", Description: "Latvia" },
    { Code: "LY", Description: "Libyan Arab Jamahiriya" },
    { Code: "MA", Description: "Morocco" },
    { Code: "MC", Description: "Monaco" },
    { Code: "MD", Description: "Moldova" },
    { Code: "ME", Description: "Montenegro" },
    { Code: "MF", Description: "Saint Martin" },
    { Code: "MG", Description: "Madagascar" },
    { Code: "MH", Description: "Marshall Islands" },
    { Code: "MK", Description: "Macedonia" },
    { Code: "ML", Description: "Mali" },
    { Code: "MM", Description: "Myanmar" },
    { Code: "MN", Description: "Mongolia" },
    { Code: "MO", Description: "Macao" },
    { Code: "MP", Description: "Northern Mariana Islands" },
    { Code: "MQ", Description: "Martinique" },
    { Code: "MR", Description: "Mauritania" },
    { Code: "MS", Description: "Montserrat" },
    { Code: "MT", Description: "Malta" },
    { Code: "MU", Description: "Mauritius" },
    { Code: "MV", Description: "Maldives" },
    { Code: "MW", Description: "Malawi" },
    { Code: "MX", Description: "Mexico" },
    { Code: "MY", Description: "Malaysia" },
    { Code: "MZ", Description: "Mozambique" },
    { Code: "NA", Description: "Namibia" },
    { Code: "NC", Description: "New Caledonia" },
    { Code: "NE", Description: "Niger" },
    { Code: "NF", Description: "Norfolk Island" },
    { Code: "NG", Description: "Nigeria" },
    { Code: "NI", Description: "Nicaragua" },
    { Code: "ML", Description: "Netherlands" },
    { Code: "NO", Description: "Norway" },
    { Code: "NP", Description: "Nepal" },
    { Code: "NR", Description: "Nauru" },
    { Code: "NU", Description: "Niue" },
    { Code: "NZ", Description: "New Zealand" },
    { Code: "OM", Description: "Oman" },
    { Code: "PA", Description: "Panama" },
    { Code: "PE", Description: "Peru" },
    { Code: "PF", Description: "French Polynesia" },
    { Code: "PG", Description: "Papua New Guinea" },
    { Code: "PH", Description: "Philippines" },
    { Code: "PK", Description: "Pakistan" },
    { Code: "PL", Description: "Poland" },
    { Code: "PM", Description: "Saint Pierre and Miquelon" },
    { Code: "PN", Description: "Pitcairn" },
    { Code: "PR", Description: "Puerto Rico" },
    { Code: "PS", Description: "Palestinian Territory, Occupied" },
    { Code: "PT", Description: "Portugal" },
    { Code: "PW", Description: "Palau" },
    { Code: "PY", Description: "Paraguay" },
    { Code: "QA", Description: "Qatar" },
    { Code: "RE", Description: "Reunion" },
    { Code: "RO", Description: "Romania" },
    { Code: "RS", Description: "Serbia" },
    { Code: "RU", Description: "Russia" },
    { Code: "RW", Description: "Rwanda" },
    { Code: "SA", Description: "Saudi Arabia" },
    { Code: "SB", Description: "Solomon Islands" },
    { Code: "SC", Description: "Seychelles" },
    { Code: "SD", Description: "Sudan" },
    { Code: "SE", Description: "Sweden" },
    { Code: "SG", Description: "Singapore" },
    { Code: "SH", Description: "Saint Helena, Ascension and Tristan Da Cunha" },
    { Code: "SI", Description: "Slovenia" },
    { Code: "SJ", Description: "Svalbard and Jan Mayen" },
    { Code: "SK", Description: "Slovakia" },
    { Code: "SL", Description: "Sierra Leone" },
    { Code: "SM", Description: "San Marino" },
    { Code: "SN", Description: "Senegal" },
    { Code: "SO", Description: "Somalia" },
    { Code: "SR", Description: "Suriname" },
    { Code: "SS", Description: "South Sudan" },
    { Code: "ST", Description: "Sao Tome and Principe" },
    { Code: "SV", Description: "El Salvador" },
    { Code: "SY", Description: "Syrian Arab Republic" },
    { Code: "SZ", Description: "Swaziland" },
    { Code: "TC", Description: "Turks and Caicos Islands" },
    { Code: "TD", Description: "Chad" },
    { Code: "TG", Description: "Togo" },
    { Code: "TH", Description: "Thailand" },
    { Code: "TJ", Description: "Tajikistan" },
    { Code: "TK", Description: "Tokelau" },
    { Code: "TL", Description: "Timor-Leste" },
    { Code: "TM", Description: "Turkmenistan" },
    { Code: "TN", Description: "Tunisia" },
    { Code: "TO", Description: "Tonga" },
    { Code: "TR", Description: "Turkey" },
    { Code: "TT", Description: "Trinidad and Tobago" },
    { Code: "TV", Description: "Tuvalu" },
    { Code: "TW", Description: "Taiwan" },
    { Code: "TZ", Description: "Tanzania, United Republic of Tanzania" },
    { Code: "UA", Description: "Ukraine" },
    { Code: "UG", Description: "Uganda" },
    { Code: "US", Description: "United States" },
    { Code: "UY", Description: "Uruguay" },
    { Code: "UZ", Description: "Uzbekistan" },
    { Code: "VA", Description: "Holy See (Vatican City State)" },
    { Code: "VC", Description: "Saint Vincent and the Grenadines" },
    { Code: "VE", Description: "Venezuela, Bolivarian Republic of Venezuela" },
    { Code: "VG", Description: "Virgin Islands, British" },
    { Code: "VI", Description: "Virgin Islands, U.S." },
    { Code: "VN", Description: "Vietnam" },
    { Code: "VU", Description: "Vanuatu" },
    { Code: "WF", Description: "Wallis and Futuna" },
    { Code: "WS", Description: "Samoa" },
    { Code: "YE", Description: "Yemen" },
    { Code: "YT", Description: "Mayotte" },
    { Code: "ZA", Description: "South Africa" },
    { Code: "ZM", Description: "Zambia" },
    { Code: "ZW", Description: "Zimbabwe" },
];

export { Countries };
