using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Common.Interfaces.PDF
{
    public interface IDebenuPdfLibrary
    {
        int AddArcToPath(double CenterX, double CenterY, double TotalAngle);
        int AddBoxToPath(double Left, double Top, double Width, double Height);
        int AddCJKFont(int CJKFontID);
        int AddCurveToPath(double CtAX, double CtAY, double CtBX, double CtBY, double EndX, double EndY);
        int AddEmbeddedFile(string FileName, string MIMEType);
        int AddFileAttachment(string Title, int EmbeddedFileID);
        int AddFormFieldChoiceSub(int Index, string SubName, string DisplayName);
        int AddFormFieldSub(int Index, string SubName);
        int AddFormFont(int FontID);
        int AddFreeTextAnnotation(double Left, double Top, double Width, double Height, string Text, int Angle, int Options);
        int AddFreeTextAnnotationEx(double Left, double Top, double Width, double Height, string Text, int Angle, int Options, int Transparency);
        int AddGlobalJavaScript(string PackageName, string JavaScript);
        int AddImageFromFile(string FileName, int Options);
        int AddImageFromFileOffset(string FileName, int Offset, int DataLength, int Options);
        int AddImageFromString(byte[] Source, int Options);
        int AddLGIDictToPage(string DictContent);
        int AddLineToPath(double EndX, double EndY);
        int AddLinkToDestination(double Left, double Top, double Width, double Height, int DestID, int Options);
        int AddLinkToEmbeddedFile(double Left, double Top, double Width, double Height, int EmbeddedFileID, string Title, string Contents, int IconType, int Transpareny);
        int AddLinkToFile(double Left, double Top, double Width, double Height, string FileName, int Page, double Position, int NewWindow, int Options);
        int AddLinkToFileDest(double Left, double Top, double Width, double Height, string FileName, string NamedDest, double Position, int NewWindow, int Options);
        int AddLinkToFileEx(double Left, double Top, double Width, double Height, string FileName, int DestPage, int NewWindow, int Options, int Zoom, int DestType, double DestLeft, double DestTop, double DestRight, double DestBottom);
        int AddLinkToJavaScript(double Left, double Top, double Width, double Height, string JavaScript, int Options);
        int AddLinkToLocalFile(double Left, double Top, double Width, double Height, string FileName, int Options);
        int AddLinkToPage(double Left, double Top, double Width, double Height, int Page, double Position, int Options);
        int AddLinkToWeb(double Left, double Top, double Width, double Height, string Link, int Options);
        int AddNoteAnnotation(double Left, double Top, int AnnotType, double PopupLeft, double PopupTop, double PopupWidth, double PopupHeight, string Title, string Contents, double Red, double Green, double Blue, int Open);
        int AddOpenTypeFontFromFile(string FileName, int Options);
        int AddOpenTypeFontFromString(byte[] Source, int Options);
        int AddPageLabels(int Start, int Style, int Offset, string Prefix);
        int AddPageMatrix(double xscale, double yscale, double xoffset, double yoffset);
        int AddRelativeLinkToFile(double Left, double Top, double Width, double Height, string FileName, int Page, double Position, int NewWindow, int Options);
        int AddRelativeLinkToFileDest(double Left, double Top, double Width, double Height, string FileName, string NamedDest, double Position, int NewWindow, int Options);
        int AddRelativeLinkToFileEx(double Left, double Top, double Width, double Height, string FileName, int DestPage, int NewWindow, int Options, int Zoom, int DestType, double DestLeft, double DestTop, double DestRight, double DestBottom);
        int AddRelativeLinkToLocalFile(double Left, double Top, double Width, double Height, string FileName, int Options);
        int AddSeparationColor(string ColorName, double C, double M, double Y, double K, int Options);
        int AddStampAnnotation(double Left, double Top, double Width, double Height, int StampType, string Title, string Contents, double Red, double Green, double Blue, int Options);
        int AddStampAnnotationFromImage(double Left, double Top, double Width, double Height, string FileName, string Title, string Contents, double Red, double Green, double Blue, int Options);
        int AddStampAnnotationFromImageID(double Left, double Top, double Width, double Height, int ImageID, string Title, string Contents, double Red, double Green, double Blue, int Options);
        int AddStandardFont(int StandardFontID);
        int AddSubsettedFont(string FontName, int CharsetIndex, string SubsetChars);
        int AddSVGAnnotationFromFile(double Left, double Top, double Width, double Height, string FileName, int Options);
        int AddSWFAnnotationFromFile(double Left, double Top, double Width, double Height, string FileName, string Title, int Options);
        int AddTextMarkupAnnotation(int MarkupType, double Left, double Top, double Width, double Height);
        int AddToFileList(string ListName, string FileName);
        int AddTrueTypeFont(string FontName, int Embed);
        int AddTrueTypeFontFromFile(string FileName);
        int AddTrueTypeFontFromString(byte[] Source);
        int AddRGBSeparationColor(string ColorName, double Red, double Green, double Blue,
            int Options);
        int AddFormFieldSubEx(int Index, string SubName, int Options);
        int AddTrueTypeSubsettedFont(string FontName, string SubsetChars, int Options);
        int AddUnicodeFontFromFile(string FontFileName, int EncodingOptions, int EmbedOptions);
        int AddUnicodeFont(string FontName, int EncodingOptions, int EmbedOptions);
        int AddTrueTypeSubsettedFontFromString(byte[] Source, string SubsetChars, int Options);
        int AddTrueTypeSubsettedFontFromFile(string FileName, string SubsetChars, int Options);
        int AddTrueTypeFontFromStringEx(byte[] Source, int Options);
        int AddTrueTypeFontFromFileEx(string FileName, int Options);
        int AddToUnicodeFontGroup(string FontGroupName, int FontID);
        int AddSignProcessOverlayText(int SignProcessID, double XPos, double YPos,
           double TextSize, string LayerName, string OverlayText);
        int AddType1Font(string FileName);
        int AddU3DAnnotationFromFile(double Left, double Top, double Width, double Height, string FileName, int Options);
        int AnalyseFile(string InputFileName, string Password);
        int AnnotationCount();
        int AnsiStringResultLength();
        int AppendSpace(double RelativeSpace);
        int AppendTableColumns(int TableID, int NewColumnCount);
        int AppendTableRows(int TableID, int NewRowCount);
        int AppendText(string Text);
        int AppendToFile(string FileName);
        byte[] AppendToString(int AppendMode);
        int ApplyStyle(string StyleName);
        int AttachAnnotToForm(int Index);
        int BalanceContentStream();
        int BalancePageTree(int Options);
        int BeginPageUpdate();
        int CapturePage(int Page);
        int CapturePageEx(int Page, int Options);
        int CharWidth(int CharCode);
        int CheckFileCompliance(string InputFileName, string Password, int ComplianceTest, int Options);
        int CheckObjects();
        int CheckPageAnnots();
        int CheckPassword(string Password);
        int ClearFileList(string ListName);
        int ClearImage(int ImageID);
        int ClearPageLabels();
        int ClearTextFormatting();
        int CreateRenderer();
        int CloneOutlineAction(int OutlineID);
        int ClonePages(int StartPage, int EndPage, int RepeatCount);
        int CloseOutline(int OutlineID);
        int ClosePath();
        int CombineContentStreams();
        int CompareOutlines(int FirstOutlineID, int SecondOutlineID);
        int CompressContent();
        int CompressFonts(int Compress);
        int CompressImages(int Compress);
        int CompressPage();
        int ContentStreamCount();
        int ContentStreamSafe();
        int CopyPageRanges(int DocumentID, string RangeList);
        int CopyPageRangesEx(int DocumentID, string RangeList, int Options);
        int CreateNewObject();
        int CreateTable(int RowCount, int ColumnCount);
        int DAAppendFile(int FileHandle);
        int DACapturePage(int FileHandle, int PageRef);
        int DACapturePageEx(int FileHandle, int PageRef, int Options);
        int DACloseFile(int FileHandle);
        int DADrawCapturedPage(int FileHandle, int DACaptureID, int DestPageRef, double PntLeft, double PntBottom, double PntWidth, double PntHeight);
        int DADrawRotatedCapturedPage(int FileHandle, int DACaptureID, int DestPageRef, double PntLeft, double PntBottom, double PntWidth, double PntHeight, double Angle);
        int DAEmbedFileStreams(int FileHandle, string RootPath);
        string DAExtractPageText(int FileHandle, int PageRef, int Options);
        int DAExtractPageTextBlocks(int FileHandle, int PageRef, int ExtractOptions);
        int DAFindPage(int FileHandle, int Page);
        int DAGetAnnotationCount(int FileHandle, int PageRef);
        int DAGetFormFieldCount(int FileHandle);
        string DAGetFormFieldTitle(int FileHandle, int FieldIndex);
        string DAGetFormFieldValue(int FileHandle, int FieldIndex);
        byte[] DAGetImageDataToString(int FileHandle, int ImageListID, int ImageIndex);
        double DAGetImageDblProperty(int FileHandle, int ImageListID, int ImageIndex, int PropertyID);
        int DAGetImageIntProperty(int FileHandle, int ImageListID, int ImageIndex, int PropertyID);
        int DAGetImageListCount(int FileHandle, int ImageListID);
        string DAGetInformation(int FileHandle, string Key);
        int DAGetObjectCount(int FileHandle);
        byte[] DAGetObjectToString(int FileHandle, int ObjectNumber);
        double DAGetPageBox(int FileHandle, int PageRef, int BoxIndex, int Dimension);
        byte[] DAGetPageContentToString(int FileHandle, int PageRef);
        int DAGetPageCount(int FileHandle);
        double DAGetPageHeight(int FileHandle, int PageRef);
        int DAGetPageImageList(int FileHandle, int PageRef);
        double DAGetPageWidth(int FileHandle, int PageRef);
        string DAGetTextBlockAsString(int TextBlockListID, int Index);
        double DAGetTextBlockBound(int TextBlockListID, int Index, int BoundIndex);
        double DAGetTextBlockCharWidth(int TextBlockListID, int Index, int CharIndex);
        double DAGetTextBlockColor(int TextBlockListID, int Index, int ColorComponent);
        int DAGetTextBlockColorType(int TextBlockListID, int Index);
        int DAGetTextBlockCount(int TextBlockListID);
        string DAGetTextBlockFontName(int TextBlockListID, int Index);
        double DAGetTextBlockFontSize(int TextBlockListID, int Index);
        string DAGetTextBlockText(int TextBlockListID, int Index);
        int DAHasPageBox(int FileHandle, int PageRef, int BoxIndex);
        int DAHidePage(int FileHandle, int PageRef);
        int DAMovePage(int FileHandle, int PageRef, int TargetPageRef, int Options);
        int DANewPage(int FileHandle);
        int DANewPages(int FileHandle, int PageCount);
        int DANormalizePage(int FileHandle, int PageRef, int NormalizeOptions);
        int DAOpenFile(string InputFileName, string Password);
        int DAOpenFileReadOnly(string InputFileName, string Password);
        int DAPageRotation(int FileHandle, int PageRef);
        int DAReleaseImageList(int FileHandle, int ImageListID);
        int DAReleaseTextBlocks(int TextBlockListID);
        int DARemoveUsageRights(int FileHandle);
        int DARenderPageToDC(int FileHandle, int PageRef, double DPI, IntPtr DC);
        int DARenderPageToFile(int FileHandle, int PageRef, int Options, double DPI, string FileName);
        byte[] DARenderPageToString(int FileHandle, int PageRef, int Options, double DPI);
        int DARotatePage(int FileHandle, int PageRef, int Angle, int Options);
        int DASaveAsFile(int FileHandle, string OutputFileName);
        int DASaveImageDataToFile(int FileHandle, int ImageListID, int ImageIndex, string ImageFileName);
        int DASetInformation(int FileHandle, string Key, string NewValue);
        int DASetPageBox(int FileHandle, int PageRef, int BoxIndex, double X1, double Y1, double X2, double Y2);
        int DASetPageLayout(int FileHandle, int NewPageLayout);
        int DASetPageMode(int FileHandle, int NewPageMode);
        int DASetPageSize(int FileHandle, int PageRef, double PntWidth, double PntHeight);
        int DASetTextExtractionArea(double Left, double Top, double Width, double Height);
        int DASetTextExtractionOptions(int OptionID, int NewValue);
        int DASetTextExtractionScaling(int Options, double Horizontal, double Vertical);
        int DASetTextExtractionWordGap(double NewWordGap);
        int DAShiftedHeader(int FileHandle);
        int Decrypt();
        int DecryptFile(string InputFileName, string OutputFileName, string Password);
        int DeleteAnalysis(int AnalysisID);
        int DeleteAnnotation(int Index);
        int DeleteContentStream();
        int DeleteFormField(int Index);
        int DeleteOptionalContentGroup(int OptionalContentGroupID);
        int DeletePageLGIDict(int DictIndex);
        int DeletePages(int StartPage, int PageCount);
        int DocJavaScriptAction(string ActionType, string JavaScript);
        int DocumentCount();
        int DrawArc(double XPos, double YPos, double Radius, double StartAngle, double EndAngle, int Pie, int DrawOptions);
        int DrawBarcode(double Left, double Top, double Width, double Height, string Text, int Barcode, int Options);
        int DrawBox(double Left, double Top, double Width, double Height, int DrawOptions);
        int DrawCapturedPage(int CaptureID, double Left, double Top, double Width, double Height);
        int DrawCapturedPageMatrix(int CaptureID, double M11, double M12, double M21, double M22, double MDX, double MDY);
        int DrawCircle(double XPos, double YPos, double Radius, int DrawOptions);
        int DrawDataMatrixSymbol(double Left, double Top, double ModuleSize, string Text, int Encoding, int SymbolSize, int Options);
        int DrawEllipse(double XPos, double YPos, double Width, double Height, int DrawOptions);
        int DrawEllipticArc(double XPos, double YPos, double Width, double Height, double StartAngle, double EndAngle, int Pie, int DrawOptions);
        int DrawHTMLText(double Left, double Top, double Width, string HTMLText);
        string DrawHTMLTextBox(double Left, double Top, double Width, double Height, string HTMLText);
        string DrawHTMLTextBoxMatrix(double Width, double Height, string HTMLText, double M11, double M12, double M21, double M22, double MDX, double MDY);
        int DrawHTMLTextMatrix(double Width, string HTMLText, double M11, double M12, double M21, double M22, double MDX, double MDY);
        int DrawImage(double Left, double Top, double Width, double Height);
        int DrawImageMatrix(double M11, double M12, double M21, double M22, double MDX, double MDY);
        int DrawIntelligentMailBarcode(double Left, double Top, double BarWidth, double FullBarHeight, double TrackerHeight, double SpaceWidth, string BarcodeData, int Options);
        int DrawLine(double StartX, double StartY, double EndX, double EndY);
        int DrawMultiLineText(double XPos, double YPos, string Delimiter, string Text);
        int DrawPath(int PathOptions);
        int DrawPathEvenOdd(int PathOptions);
        int DAGetPageMode(int FileHandle);
        int DAGetPageLayout(int FileHandle);
        int DASetRenderArea(double Left, double Top, double Width, double Height);
        int DrawPDF417Symbol(double Left, double Top, string Text, int Options);
        int DrawPDF417SymbolEx(double Left, double Top, string Text, int Options, int FixedColumns, int FixedRows, int ErrorLevel, double ModuleSize, double HeightWidthRatio);
        int DrawPostScriptXObject(int PSRef);
        int DestroyRenderer();
        int DrawQRCode(double Left, double Top, double SymbolSize, string Text, int EncodeOptions, int DrawOptions);
        int DrawRotatedBox(double Left, double Bottom, double Width, double Height, double Angle, int DrawOptions);
        int DrawRotatedCapturedPage(int CaptureID, double Left, double Bottom, double Width, double Height, double Angle);
        int DrawRotatedImage(double Left, double Bottom, double Width, double Height, double Angle);
        int DrawRotatedMultiLineText(double XPos, double YPos, double Angle, string Delimiter, string Text);
        int DrawRotatedText(double XPos, double YPos, double Angle, string Text);
        int DrawRotatedTextBox(double Left, double Top, double Width, double Height, double Angle, string Text, int Options);
        int DrawRotatedTextBoxEx(double Left, double Top, double Width, double Height, double Angle, string Text, int Options, int Border, int Radius, int DrawOptions);
        int DrawRoundedBox(double Left, double Top, double Width, double Height, double Radius, int DrawOptions);
        int DrawRoundedRotatedBox(double Left, double Bottom, double Width, double Height, double Radius, double Angle, int DrawOptions);
        int DrawScaledImage(double Left, double Top, double Scale);
        int DrawFontGroupText(string FontGroupName, double XPos, double YPos, string Text);
        int DrawSpacedText(double XPos, double YPos, double Spacing, string Text);
        double DrawTableRows(int TableID, double Left, double Top, double Height, int FirstRow, int LastRow);
        int DrawText(double XPos, double YPos, string Text);
        int DrawTextArc(double XPos, double YPos, double Radius, double Angle, string Text, int DrawOptions);
        int DrawTextBox(double Left, double Top, double Width, double Height, string Text, int Options);
        int DrawTextBoxMatrix(double Width, double Height, string Text, int Options, double M11, double M12, double M21, double M22, double MDX, double MDY);
        int DrawWrappedText(double XPos, double YPos, double Width, string Text);
        int EditableContentStream();
        int EmbeddedFileCount();
        int EmbedFile(string Title, string FileName, string MIMEType);
        int EncapsulateContentStream();
        int EncodePermissions(int CanPrint, int CanCopy, int CanChange, int CanAddNotes, int CanFillFields, int CanCopyAccess, int CanAssemble, int CanPrintFull);
        int Encrypt(string Owner, string User, int Strength, int Permissions);
        int EncryptFile(string InputFileName, string OutputFileName, string Owner, string User, int Strength, int Permissions);
        int EncryptionAlgorithm();
        int EncryptionStatus();
        int EncryptionStrength();
        int EncryptWithFingerprint(string Fingerprint);
        int DrawUniscribeText(double XPos, double YPos, string Text, int Options);
        int EndPageUpdate();
        int EmbedRelatedFile(string Title, string FileName, string MIMEType,
            string AFRelationship, int Options);
        int EndSignProcessToFile(int SignProcessID, string OutputFile);
        byte[] EndSignProcessToString(int SignProcessID);
        byte[] ExtractFilePageContentToString(string InputFileName, string Password, int Page);
        int ExtractFilePages(string InputFileName, string Password, string OutputFileName, string RangeList);
        int ExtractFilePagesEx(string InputFileName, string Password, string OutputFileName, string RangeList, int Options);
        string ExtractFilePageText(string InputFileName, string Password, int Page, int Options);
        int ExtractFilePageTextBlocks(string InputFileName, string Password, int Page, int Options);
        int ExtractPageRanges(string RangeList);
        int ExtractPages(int StartPage, int PageCount);
        int ExtractPageTextBlocks(int ExtractOptions);
        int FileListCount(string ListName);
        string FileListItem(string ListName, int Index);
        int FindFonts();
        int FindFormFieldByTitle(string Title);
        int FindImages();
        int FitImage(double Left, double Top, double Width, double Height, int HAlign, int VAlign, int Rotate);
        int FitRotatedTextBox(double Left, double Top, double Width, double Height, double Angle, string Text, int Options);
        int FitTextBox(double Left, double Top, double Width, double Height, string Text, int Options);
        int FlattenAnnot(int Index, int Options);
        int FlattenAllFormFields(int Options);
        int FlattenFormField(int Index);
        int FontCount();
        string FontFamily();
        int FontHasKerning();
        string FontName();
        string FontReference();
        int FontSize();
        int FontType();
        int FormFieldCount();
        int FormFieldHasParent(int Index);
        int FormFieldJavaScriptAction(int Index, string ActionType, string JavaScript);
        int FormFieldWebLinkAction(int Index, string ActionType, string Link);
        int GetActionDest(int ActionID);
        string GetActionType(int ActionID);
        string GetActionURL(int ActionID);
        string GetAnalysisInfo(int AnalysisID, int AnalysisItem);
        int GetAnnotActionID(int Index);
        double GetAnnotDblProperty(int Index, int Tag);
        int GetAnnotDest(int Index);
        string GetAnnotEmbeddedFileName(int Index, int Options);
        int GetAnnotEmbeddedFileToFile(int Index, int Options, string FileName);
        byte[] GetAnnotEmbeddedFileToString(int Index, int Options);
        int GetAnnotIntProperty(int Index, int Tag);
        int GetAnnotQuadCount(int Index);
        double GetAnnotQuadPoints(int Index, int QuadNumber, int PointNumber);
        int GetAnnotSoundToFile(int Index, int Options, string SoundFileName);
        byte[] GetAnnotSoundToString(int Index, int Options);
        string GetAnnotStrProperty(int Index, int Tag);
        double GetBarcodeWidth(double NominalWidth, string Text, int Barcode);
        string GetBaseURL();
        IntPtr GetCanvasDC(int CanvasWidth, int CanvasHeight);
        int GetCanvasDCEx(int CanvasWidth, int CanvasHeight, int ReferenceDC);
        string GetCatalogInformation(string Key);
        byte[] GetContentStreamToString();
        int GetCSDictEPSG(int CSDictID);
        int GetCSDictType(int CSDictID);
        string GetCSDictWKT(int CSDictID);
        string GetCustomInformation(string Key);
        string GetCustomKeys(int Location);
        string GetDefaultPrinterName();
        string GetDestName(int DestID);
        int GetDestPage(int DestID);
        int GetDestType(int DestID);
        double GetDestValue(int DestID, int ValueKey);
        string GetDocJavaScript(string ActionType);
        string GetDocumentFileName();
        int GetDocumentFileSize();
        int GetDocumentID(int Index);
        string GetDocumentIdentifier(int Part, int Options);
        string GetDocumentMetadata();
        int GetDocumentRepaired();
        string GetDocumentResourceList();
        int GetEmbeddedFileContentToFile(int Index, string FileName);
        byte[] GetEmbeddedFileContentToString(int Index);
        int GetEmbeddedFileID(int Index);
        int GetEmbeddedFileIntProperty(int Index, int Tag);
        string GetEmbeddedFileStrProperty(int Index, int Tag);
        string GetEncryptionFingerprint();
        string GetFileMetadata(string InputFileName, string Password);
        int GetFirstChildOutline(int OutlineID);
        int GetFirstOutline();
        int GetFontEncoding();
        int GetFontFlags(int FontFlagItemID);
        int GetFontID(int Index);
        int GetFontIsEmbedded();
        int GetFontIsSubsetted();
        int GetFontMetrics(int MetricType);
        int GetFontObjectNumber();
        int GetFormFieldActionID(int Index, string TriggerEvent);
        int GetFormFieldAlignment(int Index);
        int GetFormFieldAnnotFlags(int Index);
        double GetFormFieldBackgroundColor(int Index, int ColorComponent);
        int GetFormFieldBackgroundColorType(int Index);
        double GetFormFieldBorderColor(int Index, int ColorComponent);
        int GetFormFieldBorderColorType(int Index);
        double GetFormFieldBorderProperty(int Index, int PropKey);
        int GetFormFieldBorderStyle(int Index);
        double GetFormFieldBound(int Index, int Edge);
        string GetFormFieldCaption(int Index);
        string GetFormFieldCaptionEx(int Index, int StringType);
        int GetFormFieldCheckStyle(int Index);
        string GetFormFieldChildTitle(int Index);
        int GetFormFieldChoiceType(int Index);
        double GetFormFieldColor(int Index, int ColorComponent);
        int GetFormFieldComb(int Index);
        string GetFormFieldDefaultValue(int Index);
        string GetFormFieldDescription(int Index);
        int GetFormFieldFlags(int Index);
        string GetFormFieldFontName(int Index);
        string GetFormFieldJavaScript(int Index, string ActionType);
        int GetFormFieldKidCount(int Index);
        int GetFormFieldKidTempIndex(int Index, int SubIndex);
        int GetFormFieldMaxLen(int Index);
        int GetFormFieldNoExport(int Index);
        int GetFormFieldPage(int Index);
        int GetFormFieldPrintable(int Index);
        int GetFormFieldReadOnly(int Index);
        int GetFormFieldRequired(int Index);
        string GetFormFieldRichTextString(int Index, string Key);
        int GetFormFieldRotation(int Index);
        int GetFormFieldSubCount(int Index);
        string GetFormFieldSubDisplayName(int Index, int SubIndex);
        string GetFormFieldSubmitActionString(int Index, string ActionType);
        string GetFormFieldSubName(int Index, int SubIndex);
        int GetFormFieldTabOrder(int Index);
        int GetFormFieldTabOrderEx(int Index, int Options);
        int GetFormFieldTextFlags(int Index, int ValueKey);
        double GetFormFieldTextSize(int Index);
        string GetFormFieldTitle(int Index);
        int GetFormFieldType(int Index);
        string GetFormFieldValue(int Index);
        string GetFormFieldValueByTitle(string Title);
        int GetFormFieldVisible(int Index);
        string GetFormFieldWebLink(int Index, string ActionType);
        int GetFormFontCount();
        string GetFormFontName(int FontIndex);
        string GetGlobalJavaScript(string PackageName);
        double GetHTMLTextHeight(double Width, string HTMLText);
        int GetHTMLTextLineCount(double Width, string HTMLText);
        double GetHTMLTextWidth(double MaxWidth, string HTMLText);
        int GetImageID(int Index);
        int GetImageListCount(int ImageListID);
        byte[] GetImageListItemDataToString(int ImageListID, int ImageIndex, int Options);
        double GetImageListItemDblProperty(int ImageListID, int ImageIndex, int PropertyID);
        string GetImageListItemFormatDesc(int ImageListID, int ImageIndex, int Options);
        int GetImageListItemIntProperty(int ImageListID, int ImageIndex, int PropertyID);
        int GetImageMeasureDict();
        int GetImagePageCount(string FileName);
        int GetImagePageCountFromString(byte[] Source);
        int GetImagePtDataDict();
        string GetInformation(int Key);
        string GetInstalledFontsByCharset(int CharsetIndex, int Options);
        string GetInstalledFontsByCodePage(int CodePage, int Options);
        int GetKerning(string CharPair);
        string GetLatestPrinterNames();
        int GetMaxObjectNumber();
        int GetMeasureDictBoundsCount(int MeasureDictID);
        double GetMeasureDictBoundsItem(int MeasureDictID, int ItemIndex);
        int GetMeasureDictCoordinateSystem(int MeasureDictID);
        int GetMeasureDictDCSDict(int MeasureDictID);
        int GetMeasureDictGCSDict(int MeasureDictID);
        int GetMeasureDictGPTSCount(int MeasureDictID);
        double GetMeasureDictGPTSItem(int MeasureDictID, int ItemIndex);
        int GetMeasureDictLPTSCount(int MeasureDictID);
        double GetMeasureDictLPTSItem(int MeasureDictID, int ItemIndex);
        int GetMeasureDictPDU(int MeasureDictID, int UnitIndex);
        int GetNamedDestination(string DestName);
        int GetNextOutline(int OutlineID);
        int GetObjectCount();
        int GetObjectDecodeError(int ObjectNumber);
        byte[] GetObjectToString(int ObjectNumber);
        int GetOpenActionDestination();
        string GetOpenActionJavaScript();
        int GetOptionalContentConfigCount();
        int GetOptionalContentConfigLocked(int OptionalContentConfigID, int OptionalContentGroupID);
        int GetOptionalContentConfigOrderCount(int OptionalContentConfigID);
        int GetOptionalContentConfigOrderItemID(int OptionalContentConfigID, int ItemIndex);
        string GetOptionalContentConfigOrderItemLabel(int OptionalContentConfigID, int ItemIndex);
        int GetOptionalContentConfigOrderItemLevel(int OptionalContentConfigID, int ItemIndex);
        int GetOptionalContentConfigOrderItemType(int OptionalContentConfigID, int ItemIndex);
        int GetOptionalContentConfigState(int OptionalContentConfigID, int OptionalContentGroupID);
        int GetOptionalContentGroupID(int Index);
        string GetOptionalContentGroupName(int OptionalContentGroupID);
        int GetOptionalContentGroupPrintable(int OptionalContentGroupID);
        int GetOptionalContentGroupVisible(int OptionalContentGroupID);
        int GetOrigin();
        int GetOutlineActionID(int OutlineID);
        double GetOutlineColor(int OutlineID, int ColorComponent);
        int GetOutlineDest(int OutlineID);
        int GetOutlineID(int Index);
        string GetOutlineJavaScript(int OutlineID);
        int GetOutlineObjectNumber(int OutlineID);
        string GetOutlineOpenFile(int OutlineID);
        int GetOutlinePage(int OutlineID);
        int GetOutlineStyle(int OutlineID);
        string GetOutlineWebLink(int OutlineID);
        double GetPageBox(int BoxType, int Dimension);
        string GetPageColorSpaces(int Options);
        byte[] GetPageContentToString();
        int GetPageImageList(int Options);
        string GetPageJavaScript(string ActionType);
        string GetPageLabel(int Page);
        int GetPageLayout();
        string GetPageLGIDictContent(int DictIndex);
        int GetPageLGIDictCount();
        byte[] GetPageMetricsToString(int StartPage, int EndPage, int Options);
        int GetPageMode();
        string GetPageText(int ExtractOptions);
        double GetPageUserUnit();
        int GetPageViewPortCount();
        int GetPageViewPortID(int Index);
        int GetParentOutline(int OutlineID);
        int GetPrevOutline(int OutlineID);
        string GetPrinterBins(string PrinterName);
        byte[] GetPrinterDevModeToString(string PrinterName);
        string GetPrinterMediaTypes(string PrinterName);
        string GetPrinterNames();
        byte[] GetPrintPreviewBitmapToString(string PrinterName, int PreviewPage, int PrintOptions, int MaxDimension, int PreviewOptions);
        double GetRenderScale();
        int GetSignProcessByteRange(int SignProcessID, int ArrayPosition);
        int GetSignProcessResult(int SignProcessID);
        int GetStringListCount(int StringListID);
        string GetStringListItem(int StringListID, int ItemIndex);
        double GetTableCellDblProperty(int TableID, int RowNumber, int ColumnNumber, int Tag);
        int GetTableCellIntProperty(int TableID, int RowNumber, int ColumnNumber, int Tag);
        string GetTableCellStrProperty(int TableID, int RowNumber, int ColumnNumber, int Tag);
        int GetTableColumnCount(int TableID);
        int GetTableLastDrawnRow(int TableID);
        int GetMeasurementUnits();
        byte[] GetFontCharacterCodesToString(string InputText);
        int GetTableRowCount(int TableID);
        int GetNeedAppearances();
        string GetTabOrderMode();
        string GetTempPath();
        double GetTextAscent();
        string GetTextBlockAsString(int TextBlockListID, int Index);
        double GetTextBlockBound(int TextBlockListID, int Index, int BoundIndex);
        double GetTextBlockCharWidth(int TextBlockListID, int Index, int CharIndex);
        double GetTextBlockColor(int TextBlockListID, int Index, int ColorComponent);
        int GetTextBlockColorType(int TextBlockListID, int Index);
        int GetTextBlockCount(int TextBlockListID);
        string GetTextBlockFontName(int TextBlockListID, int Index);
        double GetTextBlockFontSize(int TextBlockListID, int Index);
        string GetTextBlockText(int TextBlockListID, int Index);
        double GetTextBound(int Edge);
        double GetTextDescent();
        double GetTextHeight();
        double GetTextSize();
        double GetScale();
        double GetPDF417SymbolWidth(string Text, int Options, int FixedColumns, int FixedRows,
            int ErrorLevel, double ModuleSize, double HeightWidthRatio);
        double GetPDF417SymbolHeight(string Text, int Options, int FixedColumns,
            int FixedRows, int ErrorLevel, double ModuleSize, double HeightWidthRatio);
        double GetTextWidth(string Text);
        string GetUnicodeCharactersFromEncoding(int Encoding);
        int GetViewerPreferences(int Option);
        double GetViewPortBBox(int ViewPortID, int Dimension);
        int GetViewPortMeasureDict(int ViewPortID);
        string GetViewPortName(int ViewPortID);
        int GetViewPortPtDataDict(int ViewPortID);
        string GetWrappedText(double Width, string Delimiter, string Text);
        string GetWrappedTextBreakString(double Width, string Delimiter, string Text);
        double GetWrappedTextHeight(double Width, string Text);
        int GetWrappedTextLineCount(double Width, string Text);
        int GetXFAFormFieldCount();
        string GetXFAFormFieldName(int Index);
        string GetXFAFormFieldNames(string Delimiter);
        string GetXFAFormFieldValue(string XFAFieldName);
        byte[] GetXFAToString(int Options);
        int GlobalJavaScriptCount();
        string GlobalJavaScriptPackageName(int Index);
        int HasFontResources();
        int HasPageBox(int BoxType);
        int HidePage();
        int ImageCount();
        int ImageFillColor();
        int ImageHeight();
        int ImageHorizontalResolution();
        int ImageResolutionUnits();
        int ImageType();
        int ImageVerticalResolution();
        int ImageWidth();
        int ImportEMFFromFile(string FileName, int FontOptions, int GeneralOptions);
        int InsertPages(int StartPage, int PageCount);
        int InsertTableColumns(int TableID, int Position, int NewColumnCount);
        int InsertTableRows(int TableID, int Position, int NewRowCount);
        int IsAnnotFormField(int Index);
        int IsLinearized();
        int IsTaggedPDF();
        int LastErrorCode();
        string LastRenderError();
        bool LibraryLoaded();
        string LibraryVersion();
        string LibraryVersionEx();
        string LicenseInfo();
        int LinearizeFile(string InputFileName, string Password, string OutputFileName, int Options);
        int LoadFromCanvasDC(double DPI, int Options);
        int LoadFromFile(string FileName, string Password);
        int LoadFromString(byte[] Source, string Password);
        int LoadState();
        int MergeDocument(int DocumentID);
        int MergeFileList(string ListName, string OutputFileName);
        int MergeFileListFast(string ListName, string OutputFileName);
        int MergeFiles(string FirstFileName, string SecondFileName, string OutputFileName);
        int MergeTableCells(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn);
        int MoveContentStream(int FromPosition, int ToPosition);
        int MoveOutlineAfter(int OutlineID, int SiblingID);
        int MoveOutlineBefore(int OutlineID, int SiblingID);
        int MovePage(int NewPosition);
        int MovePath(double NewX, double NewY);
        int MultiplyScale(double MultScaleBy);
        int NewChildFormField(int Index, string Title, int FieldType);
        int NewContentStream();
        string NewCustomPrinter(string OriginalPrinterName);
        int NewDestination(int DestPage, int Zoom, int DestType, double Left, double Top, double Right, double Bottom);
        int NewDocument();
        int NewFormField(string Title, int FieldType);
        int NewInternalPrinterObject(int Options);
        int NewNamedDestination(string DestName, int DestID);
        int NewOptionalContentGroup(string GroupName);
        int NewOutline(int Parent, string Title, int DestPage, double DestPosition);
        int NewPage();
        int NewPageFromCanvasDC(double DPI, int Options);
        int NewPages(int PageCount);
        int NewCMYKAxialShader(string ShaderName, double StartX, double StartY,
            double StartCyan, double StartMagenta, double StartYellow, double StartBlack,
            double EndX, double EndY, double EndCyan, double EndMagenta, double EndYellow,
            double EndBlack, int Extend);
        int NewPostScriptXObject(string PS);
        int NewRGBAxialShader(string ShaderName, double StartX, double StartY, double StartRed, double StartGreen, double StartBlue, double EndX, double EndY, double EndRed, double EndGreen, double EndBlue, int Extend);
        int NewSignProcessFromFile(string InputFile, string Password);
        int NewSignProcessFromString(byte[] Source, string Password);
        int NewStaticOutline(int Parent, string Title);
        int NewTilingPatternFromCapturedPage(string PatternName, int CaptureID);
        int NoEmbedFontListAdd(string FontName);
        int NoEmbedFontListCount();
        string NoEmbedFontListGet(int Index);
        int NoEmbedFontListRemoveAll();
        int NoEmbedFontListRemoveIndex(int Index);
        int NoEmbedFontListRemoveName(string FontName);
        int NormalizePage(int NormalizeOptions);
        int OpenOutline(int OutlineID);
        int OptionalContentGroupCount();
        int OutlineCount();
        string OutlineTitle(int OutlineID);
        int PageCount();
        int PageHasFontResources(int PageNumber);
        int PDFiumPrintDocument(string PrinterName, int StartPage, int EndPage, int Options);

        double PageHeight();
        int PageJavaScriptAction(string ActionType, string JavaScript);
        int PageRotation();
        double PageWidth();
        int PrintDocument(string PrinterName, int StartPage, int EndPage, int Options);
        int PrintDocumentToFile(string PrinterName, int StartPage, int EndPage, int Options, string FileName);
        int PrintMode(int Mode);
        int PrintOptions(int PageScaling, int AutoRotateCenter, string Title);
        int PrintPages(string PrinterName, string PageRanges, int Options);
        int PrintPagesToFile(string PrinterName, string PageRanges, int Options, string FileName);
        int ReleaseImage(int ImageID);
        int ReleaseImageList(int ImageListID);
        void ReleaseLibrary();
        int ReleaseSignProcess(int SignProcessID);
        int ReleaseStringList(int StringListID);
        int ReleaseTextBlocks(int TextBlockListID);
        int RemoveAppearanceStream(int Index);
        int RemoveCustomInformation(string Key);
        int RemoveDocument(int DocumentID);
        int RemoveEmbeddedFile(int Index);
        int RemoveFormFieldBackgroundColor(int Index);
        int RemoveFormFieldBorderColor(int Index);
        int RemoveFormFieldChoiceSub(int Index, string SubName);
        int RemoveGlobalJavaScript(string PackageName);
        int RemoveOpenAction();
        int RemoveOutline(int OutlineID);
        int RemovePageBox(int BoxType);
        int RemoveSharedContentStreams();
        int RemoveStyle(string StyleName);
        int RemoveUsageRights();
        int RemoveXFAEntries(int Options);
        int ReduceSize(int Options);

        int RenderAsMultipageTIFFToFile(double DPI, string PageRanges, int ImageOptions, int OutputOptions, string FileName);
        int RenderDocumentToFile(double DPI, int StartPage, int EndPage, int Options, string FileName);
        int RenderPageToDC(double DPI, int Page, IntPtr DC);
        int RenderPageToFile(double DPI, int Page, int Options, string FileName);
        byte[] RenderPageToString(double DPI, int Page, int Options);
        int ReplaceFonts(int Options);
        int ReplaceImage(int OriginalImageID, int NewImageID);
        int ReplaceTag(string Tag, string NewValue);
        int RequestPrinterStatus(int StatusCommand);
        int RetrieveCustomDataToFile(string Key, string FileName, int Location);
        byte[] RetrieveCustomDataToString(string Key, int Location);
        int ReverseImage(int Reset);
        int RotatePage(int PageRotation);
        int SaveFontToFile(string FileName);
        int SaveImageListItemDataToFile(int ImageListID, int ImageIndex, int Options, string ImageFileName);
        int SaveImageToFile(string FileName);
        byte[] SaveImageToString();
        int SaveState();
        int SaveStyle(string StyleName);
        int SaveToFile(string FileName);
        byte[] SaveToString();
        int SecurityInfo(int SecurityItem);
        int SelectContentStream(int NewIndex);
        int SelectDocument(int DocumentID);
        int SelectedDocument();
        int SelectedFont();
        int SelectedImage();
        int SelectedPage();
        int SelectFont(int FontID);
        int SelectImage(int ImageID);
        int SelectPage(int PageNumber);
        int SelectRenderer(int RendererID);
        int SetActionURL(int ActionID, string NewURL);
        int SetAnnotBorderColor(int Index, double Red, double Green, double Blue);
        int SetAnnotBorderStyle(int Index, double Width, int Style, double DashOn, double DashOff);
        int SetAnnotContents(int Index, string NewContents);
        int SetAnnotDblProperty(int Index, int Tag, double NewValue);
        int SetAnnotIntProperty(int Index, int Tag, int NewValue);
        int SetAnnotOptional(int Index, int OptionalContentGroupID);
        int SetAnnotQuadPoints(int Index, int QuadNumber, double X1, double Y1, double X2, double Y2, double X3, double Y3, double X4, double Y4);
        int SetAnnotRect(int Index, double Left, double Top, double Width, double Height);
        int SetAnnotStrProperty(int Index, int Tag, string NewValue);
        int SetAnsiMode(int NewAnsiMode);
        int SetAppendInputFromString(byte[] Source);
        int SetBaseURL(string NewBaseURL);
        int SetBlendMode(int BlendMode);
        int SetBreakString(string NewBreakString);
        int SetCairoFileName(string FileName);
        int SetCapturedPageOptional(int CaptureID, int OptionalContentGroupID);
        int SetCapturedPageTransparencyGroup(int CaptureID, int CS, int Isolate, int Knockout);
        int SetCatalogInformation(string Key, string NewValue);
        int SetCharWidth(int CharCode, int NewWidth);
        int SetClippingPath();
        int SetClippingPathEvenOdd();
        int SetCompatibility(int CompatibilityItem, int CompatibilityMode);
        int SetContentStreamFromString(byte[] Source);
        int SetContentStreamOptional(int OptionalContentGroupID);
        int SetCropBox(double Left, double Top, double Width, double Height);
        int SetCSDictEPSG(int CSDictID, int NewEPSG);
        int SetCSDictType(int CSDictID, int NewDictType);
        int SetCSDictWKT(int CSDictID, string NewWKT);
        int SetCustomInformation(string Key, string NewValue);
        int SetCustomLineDash(string DashPattern, double DashPhase);
        int SetDecodeMode(int NewDecodeMode);
        int SetDestProperties(int DestID, int Zoom, int DestType, double Left, double Top, double Right, double Bottom);
        int SetDestValue(int DestID, int ValueKey, double NewValue);
        int SetDocumentMetadata(string XMP);
        int SetDPLRFileName(string FileName);
        int SetEmbeddedFileStrProperty(int Index, int Tag, string NewValue);
        int SetFillColor(double Red, double Green, double Blue);
        int SetFillColorCMYK(double C, double M, double Y, double K);
        int SetFillColorSep(string ColorName, double Tint);
        int SetFillShader(string ShaderName);
        int SetFillTilingPattern(string PatternName);
        int SetFindImagesMode(int NewFindImagesMode);
        int SetFontEncoding(int Encoding);
        int SetFontFlags(int Fixed, int Serif, int Symbolic, int Script, int Italic, int AllCap, int SmallCap, int ForceBold);
        int SetFormFieldAlignment(int Index, int Alignment);
        int SetFormFieldAnnotFlags(int Index, int NewFlags);
        int SetFormFieldBackgroundColor(int Index, double Red, double Green, double Blue);
        int SetFormFieldBackgroundColorCMYK(int Index, double C, double M, double Y, double K);
        int SetFormFieldBackgroundColorGray(int Index, double Gray);
        int SetFormFieldBackgroundColorSep(int Index, string ColorName, double Tint);
        int SetFormFieldBorderColor(int Index, double Red, double Green, double Blue);
        int SetFormFieldBorderColorCMYK(int Index, double C, double M, double Y, double K);
        int SetFormFieldBorderColorGray(int Index, double Gray);
        int SetFormFieldBorderColorSep(int Index, string ColorName, double Tint);
        int SetFormFieldBorderStyle(int Index, double Width, int Style, double DashOn, double DashOff);
        int SetFormFieldBounds(int Index, double Left, double Top, double Width, double Height);
        int SetFormFieldCalcOrder(int Index, int Order);
        int SetFormFieldCaption(int Index, string NewCaption);
        int SetFormFieldCheckStyle(int Index, int CheckStyle, int Position);
        int SetFormFieldChildTitle(int Index, string NewTitle);
        int SetFormFieldChoiceSub(int Index, int SubIndex, string SubName, string DisplayName);
        int SetFormFieldChoiceType(int Index, int ChoiceType);
        int SetFormFieldColor(int Index, double Red, double Green, double Blue);
        int SetFormFieldColorCMYK(int Index, double C, double M, double Y, double K);
        int SetFormFieldColorSep(int Index, string ColorName, double Tint);
        int SetFormFieldComb(int Index, int Comb);
        int SetFormFieldDefaultValue(int Index, string NewDefaultValue);
        int SetFormFieldDescription(int Index, string NewDescription);
        int SetFormFieldFlags(int Index, int NewFlags);
        int SetFormFieldFont(int Index, int FontIndex);
        int SetFormFieldHighlightMode(int Index, int NewMode);
        int SetFormFieldIcon(int Index, int IconType, int CaptureID);
        int SetFormFieldIconStyle(int Index, int Placement, int Scale, int ScaleType, int HorizontalShift, int VerticalShift);
        int SetFormFieldMaxLen(int Index, int NewMaxLen);
        int SetFormFieldNoExport(int Index, int NoExport);
        int SetFormFieldOptional(int Index, int OptionalContentGroupID);
        int SetFormFieldPage(int Index, int NewPage);
        int SetFormFieldPrintable(int Index, int Printable);
        int SetFormFieldReadOnly(int Index, int ReadOnly);
        int SetFormFieldRequired(int Index, int Required);
        int SetFormFieldResetAction(int Index, string ActionType);
        int SetFormFieldRichTextString(int Index, string Key, string NewValue);
        int SetFormFieldRotation(int Index, int Angle);
        int SetFormFieldSignatureImage(int Index, int ImageID, int Options);
        int SetFormFieldStandardFont(int Index, int StandardFontID);
        int SetFormFieldSubmitAction(int Index, string ActionType, string Link);
        int SetFormFieldLockAction(int Index, int LockAction, string FieldList,
            string Delimiter);
        int SetFormFieldCustomDict(int Index, string Key, string NewValue, int StorageType,
            int Options);
        int SetFormFieldCheckboxColor(int Index, int SetType, double Red, double Green,
            double Blue);
        int SetFormFieldAppearanceFromString(int Index, byte[] Source, int FontID,
            string FontReference);
        int SelectedRenderer();

        int SetFormFieldDefaultValueEx(int Index, string NewDefaultValue, int Options);
        int SetFormFieldFormatMode(int NewFormatMode);
        int SetFormFieldSubmitActionEx(int Index, string ActionType, string Link, int Flags);
        int SetFormFieldTabOrder(int Index, int Order);
        int SetFormFieldMetadata(int Index, string XMP);
        int SetFormFieldTextFlags(int Index, int Multiline, int Password, int FileSelect, int DoNotSpellCheck, int DoNotScroll);
        int SetFormFieldTextSize(int Index, double NewTextSize);
        int SetFormFieldTitle(int Index, string NewTitle);
        int SetFormFieldValueEx(int Index, string NewValue, int Options);
        int SetFormFieldValue(int Index, string NewValue);
        int SetFormFieldValueByTitle(string Title, string NewValue);
        int SetFormFieldVisible(int Index, int Visible);
        int SetGDIPlusFileName(string DLLFileName);
        int SetGDIPlusOptions(int OptionID, int NewValue);
        int SetHeaderCommentsFromString(byte[] Source);
        int SetHTMLBoldFont(string FontSet, int FontID);
        int SetHTMLBoldItalicFont(string FontSet, int FontID);
        int SetHTMLItalicFont(string FontSet, int FontID);
        int SetHTMLNormalFont(string FontSet, int FontID);
        int SetImageAsMask(int MaskType);
        int SetImageMask(double FromRed, double FromGreen, double FromBlue, double ToRed, double ToGreen, double ToBlue);
        int SetImageMaskCMYK(double FromC, double FromM, double FromY, double FromK, double ToC, double ToM, double ToY, double ToK);
        int SetImageMaskFromImage(int ImageID);
        int SetImageOptional(int OptionalContentGroupID);
        int SetImageResolution(int Horizontal, int Vertical, int Units);
        int SetInformation(int Key, string NewValue);
        int SetJavaScriptMode(int JSMode);
        int SetJPEGQuality(int Quality);
        int SetKerning(string CharPair, int Adjustment);
        int SetLineCap(int LineCap);
        int SetLineColor(double Red, double Green, double Blue);
        int SetLineColorCMYK(double C, double M, double Y, double K);
        int SetLineColorSep(string ColorName, double Tint);
        int SetLineDash(double DashOn, double DashOff);
        int SetLineDashEx(string DashValues);
        int SetLineJoin(int LineJoin);
        int SetLineShader(string ShaderName);
        int SetLineWidth(double LineWidth);
        int SetMarkupAnnotStyle(int Index, double Red, double Green, double Blue, double Transparency);
        int SetMeasureDictBoundsCount(int MeasureDictID, int NewCount);
        int SetMeasureDictBoundsItem(int MeasureDictID, int ItemIndex, double NewValue);
        int SetMeasureDictCoordinateSystem(int MeasureDictID, int CoordinateSystemID);
        int SetMeasureDictGPTSCount(int MeasureDictID, int NewCount);
        int SetMeasureDictGPTSItem(int MeasureDictID, int ItemIndex, double NewValue);
        int SetMeasureDictLPTSCount(int MeasureDictID, int NewCount);
        int SetMeasureDictLPTSItem(int MeasureDictID, int ItemIndex, double NewValue);
        int SetMeasureDictPDU(int MeasureDictID, int LinearUnit, int AreaUnit, int AngularUnit);
        int SetMeasurementUnits(int MeasurementUnits);
        int SetMetafileMode(int Mode);
        int SetNeedAppearances(int NewValue);
        int SetObjectFromString(int ObjectNumber, byte[] Source);
        int SetOpenActionDestination(int OpenPage, int Zoom);
        int SetOpenActionDestinationFull(int OpenPage, int Zoom, int DestType, double Left, double Top, double Right, double Bottom);
        int SetOpenActionJavaScript(string JavaScript);
        int SetOpenActionMenu(string MenuItem);
        int SetOptionalContentConfigLocked(int OptionalContentConfigID, int OptionalContentGroupID, int NewLocked);
        int SetOptionalContentConfigState(int OptionalContentConfigID, int OptionalContentGroupID, int NewState);
        int SetOptionalContentGroupName(int OptionalContentGroupID, string NewGroupName);
        int SetOptionalContentGroupPrintable(int OptionalContentGroupID, int Printable);
        int SetOptionalContentGroupVisible(int OptionalContentGroupID, int Visible);
        int SetOrigin(int Origin);
        int SetOutlineColor(int OutlineID, double Red, double Green, double Blue);
        int SetOutlineDestination(int OutlineID, int DestPage, double DestPosition);
        int SetOutlineDestinationFull(int OutlineID, int DestPage, int Zoom, int DestType, double Left, double Top, double Right, double Bottom);
        int SetOutlineDestinationZoom(int OutlineID, int DestPage, double DestPosition, int Zoom);
        int SetOutlineJavaScript(int OutlineID, string JavaScript);
        int SetObjectAsStreamFromString(int ObjectNumber, byte[] Source, int Options);
        int SetOutlineNamedDestination(int OutlineID, string DestName);
        int SetOutlineOpenFile(int OutlineID, string FileName);
        int SetOutlineRemoteDestination(int OutlineID, string FileName, int OpenPage, int Zoom, int DestType, double PntLeft, double PntTop, double PntRight, double PntBottom, int NewWindow);
        int SetOutlineStyle(int OutlineID, int SetItalic, int SetBold);
        int SetPDFiumRenderFlags(int NewRenderFlags);
        int SetOutlineTitle(int OutlineID, string NewTitle);
        int SetOutlineWebLink(int OutlineID, string Link);
        int SetOverprint(int StrokingOverprint, int OtherOverprint, int OverprintMode);
        int SetPageActionMenu(string MenuItem);
        int SetPageBox(int BoxType, double Left, double Top, double Width, double Height);
        int SetPDFiumFileName(string FileName);
        int SetPageContentFromString(byte[] Source);
        int SetPageDimensions(double NewPageWidth, double NewPageHeight);
        int SetPageLayout(int NewPageLayout);
        int SetPageMode(int NewPageMode);
        int SetPageSize(string PaperName);
        int SetPageThumbnail();
        int SetPageMetadata(string XMP);
        int SetPageTransparencyGroup(int CS, int Isolate, int Knockout);
        int SetPageUserUnit(double UserUnit);
        int SetPDFAMode(int NewMode);
        int SetPNGTransparencyColor(int RedByte, int GreenByte, int BlueByte);
        int SetPrecision(int NewPrecision);
        int SetPrinterDevModeFromString(byte[] Source);
        int SetRenderArea(double Left, double Top, double Width, double Height);
        int SetRenderCropType(int NewCropType);
        int SetRenderDCErasePage(int NewErasePage);
        int SetRenderDCOffset(int NewOffsetX, int NewOffsetY);
        int SetRenderOptions(int OptionID, int NewValue);
        int SetRenderScale(double NewScale);
        int SetScale(double NewScale);
        int SetSignProcessFieldLocked(int SignProcessID, int LockFieldAfterSign);
        int SetSignProcessCertFromStore(int SignProcessID, string CertHash, int Options);
        int SetSignProcessAppearanceFromString(int SignProcessID, string LayerName,
            byte[] Source);
        int SetSignProcessImageLayer(int SignProcessID, string LayerName);
        int SetSignProcessFieldMetadata(int SignProcessID, string XMP);
        int SetSignProcessCustomDict(int SignProcessID, string Key, string NewValue, int StorageType);
        int SetSignProcessCustomSubFilter(int SignProcessID, string SubFilterStr);
        int SetSignProcessField(int SignProcessID, string SignatureFieldName);
        int SetSignProcessOpenSSLFileName(int SignProcessID, string FileName);
        int SetSignProcessOptions(int SignProcessID, int OptionID, int OptionValue);
        int SetSignProcessFieldBounds(int SignProcessID, double Left, double Top, double Width, double Height);
        int SetSignProcessFieldImageFromFile(int SignProcessID, string ImageFileName, int Options);
        int SetSignProcessFieldImageFromString(int SignProcessID, byte[] Source, int Options);
        int SetSignProcessFieldPage(int SignProcessID, int SignaturePage);
        int SetSignProcessInfo(int SignProcessID, string Reason, string Location, string ContactInfo);
        int SetSignProcessKeyset(int SignProcessID, int KeysetID);
        int SetSignProcessPassthrough(int SignProcessID, int SignatureLength);
        int SetSignProcessPFXFromFile(int SignProcessID, string PFXFileName, string PFXPassword);
        int SetSignProcessPFXFromString(int SignProcessID, byte[] Source, string PFXPassword);
        int SetSignProcessSubFilter(int SignProcessID, int SubFilter);
        int SetSignProcessTimestampURL(int SignProcessID, string TimestampURL, int Options);
        int SetTableBorderColor(int TableID, int BorderIndex, double Red, double Green, double Blue);
        int SetTableBorderColorCMYK(int TableID, int BorderIndex, double C, double M, double Y, double K);
        int SetTableBorderWidth(int TableID, int BorderIndex, double NewWidth);
        int SetTableCellAlignment(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, int NewCellAlignment);
        int SetTableCellBackgroundColor(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, double Red, double Green, double Blue);
        int SetTableCellBackgroundColorCMYK(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, double C, double M, double Y, double K);
        int SetTableCellBorderColor(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, int BorderIndex, double Red, double Green, double Blue);
        int SetTableCellBorderColorCMYK(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, int BorderIndex, double C, double M, double Y, double K);
        int SetTableCellBorderWidth(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, int BorderIndex, double NewWidth);
        int SetTableCellContent(int TableID, int RowNumber, int ColumnNumber, string HTMLText);
        int SetTableCellPadding(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, int BorderIndex, double NewPadding);
        int SetTableCellTextColor(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, double Red, double Green, double Blue);
        int SetTableCellTextColorCMYK(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, double C, double M, double Y, double K);
        int SetTableCellTextSize(int TableID, int FirstRow, int FirstColumn, int LastRow, int LastColumn, double NewTextSize);
        int SetTableColumnWidth(int TableID, int FirstColumn, int LastColumn, double NewWidth);
        int SetTableRowHeight(int TableID, int FirstRow, int LastRow, double NewHeight);
        int SetTableThinBorders(int TableID, int ThinBorders, double Red, double Green, double Blue);
        int SetTableThinBordersCMYK(int TableID, int ThinBorders, double C, double M, double Y, double K);
        int SetTabOrderMode(string Mode);
        int SetTempFile(string FileName);
        int SetTempPath(string NewPath);
        int SetTextAlign(int TextAlign);
        int SetTextCharSpacing(double CharSpacing);
        int SetTextColor(double Red, double Green, double Blue);
        int SetTextColorCMYK(double C, double M, double Y, double K);
        int SetTextColorSep(string ColorName, double Tint);
        int SetTextExtractionArea(double Left, double Top, double Width, double Height);
        int SetTextExtractionOptions(int OptionID, int NewValue);
        int SetTextExtractionScaling(int Options, double Horizontal, double Vertical);
        int SetTextExtractionWordGap(double NewWordGap);
        int SetTextHighlight(int Highlight);
        int SetTextHighlightColor(double Red, double Green, double Blue);
        int SetTextHighlightColorCMYK(double C, double M, double Y, double K);
        int SetTextHighlightColorSep(string ColorName, double Tint);
        int SetTextMode(int TextMode);
        int SetTextRise(double Rise);
        int SetTextScaling(double ScalePercentage);
        int SetTextShader(string ShaderName);
        int SetTextSize(double TextSize);
        int SetTextSpacing(double Spacing);
        int SetTextUnderline(int Underline);
        int SetTextUnderlineColor(double Red, double Green, double Blue);
        int SetTextUnderlineColorCMYK(double C, double M, double Y, double K);
        int SetTextUnderlineColorSep(string ColorName, double Tint);
        int SetTextUnderlineCustomDash(string DashPattern, double DashPhase);
        int SetTextUnderlineDash(double DashOn, double DashOff);
        int SetTextUnderlineDistance(double UnderlineDistance);
        int SetTextUnderlineWidth(double UnderlineWidth);
        int SetTextWordSpacing(double WordSpacing);
        int SetTransparency(int Transparency);
        int SetupCustomPrinter(string CustomPrinterName, int Setting, int NewValue);
        int SetViewerPreferences(int Option, int NewValue);
        int SetXFAFormFieldAccess(string XFAFieldName, int NewAccess);
        int SetXFAFormFieldBorderColor(string XFAFieldName, double Red, double Green, double Blue);
        int SetXFAFormFieldBorderPresence(string XFAFieldName, int NewPresence);
        int SetXFAFormFieldBorderWidth(string XFAFieldName, double BorderWidth);
        int SetXFAFormFieldValue(string XFAFieldName, string NewValue);
        int SetXFAFromString(byte[] Source, int Options);
        int SetUpdateMode(int NewUpdateMode);
        int SignFile(string InputFileName, string OpenPassword, string SignatureFieldName, string OutputFileName, string PFXFileName, string PFXPassword, string Reason, string Location, string ContactInfo);
        int SplitPageText(int Options);
        int StartPath(double StartX, double StartY);
        int StoreCustomDataFromFile(string Key, string FileName, int Location, int Options);
        int StoreCustomDataFromString(string Key, byte[] NewValue, int Location, int Options);
        int StringResultLength();
        int TestTempPath();
        int TransformFile(string InputFileName, string Password, string OutputFileName, int TransformType, int Options);
        int Unlocked();
        int UnlockKey(string LicenseKey);
        int UpdateAndFlattenFormField(int Index);
        int UpdateAppearanceStream(int Index);
        int UpdateTrueTypeSubsettedFont(string SubsetChars);
        int UseKerning(int Kern);
        int UseUnsafeContentStreams(int SafetyLevel);
    }
}
