// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(WeSignEntities))]
    [Migration("20200430061445_addAdminUser")]
    partial class addAdminUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.DAOs.Companies.CompanyConfigurationDAO", b =>
                {
                    b.Property<Guid>("CompanyId");

                    b.Property<int>("DeleteSignedDocumentAfterXDays");

                    b.Property<int>("DeleteUnsignedDocumentAfterXDays");

                    b.Property<int>("Language");

                    b.Property<bool>("ShouldNotifyWhileSignerSigned");

                    b.Property<bool>("ShouldSendSignedDocument");

                    b.Property<string>("SignatureColor");

                    b.Property<int>("SignerLinkExpirationInDays");

                    b.HasKey("CompanyId");

                    b.ToTable("CompanyConfigurations");
                });

            modelBuilder.Entity("DAL.DAOs.Companies.CompanyDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid>("ProgramId");

                    b.Property<Guid?>("ProgramUtilizationId");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.HasIndex("ProgramId");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Name = "Free Accounts",
                            ProgramId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Status = 0
                        });
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.CompanyMessageDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("Content");

                    b.Property<int>("MessageType");

                    b.Property<int>("SendingMethod");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("CompanyMessages");
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.ConfigurationDAO", b =>
                {
                    b.Property<string>("Key");

                    b.Property<string>("Value");

                    b.HasKey("Key");

                    b.ToTable("Configuration");

                    b.HasData(
                        new
                        {
                            Key = "SmtpServer",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpPort",
                            Value = "25"
                        },
                        new
                        {
                            Key = "SmtpUser",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpPassword",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpFrom",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmtpEnableSsl",
                            Value = "False"
                        },
                        new
                        {
                            Key = "SmtpAttachmentMaxSize",
                            Value = "8388608"
                        },
                        new
                        {
                            Key = "SmsUser",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmsPassword",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmsFrom",
                            Value = ""
                        },
                        new
                        {
                            Key = "SmsProvider",
                            Value = "1"
                        },
                        new
                        {
                            Key = "SmsLanguage",
                            Value = "1"
                        },
                        new
                        {
                            Key = "DeleteSignedDocumentAfterXDays",
                            Value = "14"
                        },
                        new
                        {
                            Key = "DeleteUnsignedDocumentAfterXDays",
                            Value = "30"
                        },
                        new
                        {
                            Key = "MessageBefore",
                            Value = "[DOCUMENT_NAME] : [LINK]"
                        },
                        new
                        {
                            Key = "MessageAfter",
                            Value = "[DOCUMENT_NAME] signed successfully. [LINK]"
                        },
                        new
                        {
                            Key = "LogArichveIntervalInDays",
                            Value = "14"
                        });
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.MessageProviderDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<string>("From");

                    b.Property<string>("Password");

                    b.Property<int>("Port");

                    b.Property<int>("ProviderType");

                    b.Property<int>("SendingMethod");

                    b.Property<string>("Server");

                    b.Property<string>("User");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("MessageProviders");
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.UserConfigurationDAO", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<int>("Language");

                    b.Property<bool>("ShouldNotifyWhileSignerSigned");

                    b.Property<bool>("ShouldSendSignedDocument");

                    b.Property<string>("SignatureColor");

                    b.HasKey("UserId");

                    b.ToTable("UserConfigurations");
                });

            modelBuilder.Entity("DAL.DAOs.Contacts.ContactDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("DefaultSendingMethod");

                    b.Property<string>("Email");

                    b.Property<Guid>("GroupId");

                    b.Property<string>("Name");

                    b.Property<string>("Phone");

                    b.Property<int>("Status");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("DAL.DAOs.Contacts.ContactSealsDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContactId");

                    b.Property<string>("Name");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.ToTable("ContactSeals");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.DocumentCollectionDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("GroupId");

                    b.Property<int>("Mode");

                    b.Property<string>("Name");

                    b.Property<string>("RedirectUrl");

                    b.Property<bool?>("ShouldSend");

                    b.Property<bool?>("ShouldSendSignedDocument");

                    b.Property<DateTime>("SignedTime");

                    b.Property<int>("Status");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DocumentCollections");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.DocumentDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DocumentCollectionId");

                    b.Property<string>("Name");

                    b.Property<Guid>("TemplateId");

                    b.HasKey("Id");

                    b.HasIndex("DocumentCollectionId");

                    b.HasIndex("TemplateId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.DocumentSignatureFieldDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DocumentId");

                    b.Property<string>("FieldName");

                    b.Property<string>("Image");

                    b.HasKey("Id");

                    b.ToTable("DocumentSignatureFields");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.SignerFieldDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DocumentId");

                    b.Property<string>("FieldName");

                    b.Property<Guid>("SignerId");

                    b.HasKey("Id");

                    b.HasIndex("SignerId");

                    b.ToTable("SignerFields");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.NotesDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("SignerId");

                    b.Property<string>("SignerNote");

                    b.Property<string>("UserNote");

                    b.HasKey("Id");

                    b.HasIndex("SignerId")
                        .IsUnique();

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.SignerAttachmentDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("IsMandatory");

                    b.Property<string>("Name");

                    b.Property<Guid>("SignerId");

                    b.HasKey("Id");

                    b.HasIndex("SignerId");

                    b.ToTable("SignerAttachments");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.SignerDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ContactId");

                    b.Property<Guid>("DocumentCollectionId");

                    b.Property<int>("SendingMethod");

                    b.Property<int>("Status");

                    b.Property<DateTime>("TimeRejected");

                    b.Property<DateTime?>("TimeSent");

                    b.Property<DateTime>("TimeSigned");

                    b.Property<DateTime>("TimeViewed");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("DocumentCollectionId");

                    b.ToTable("Signers");
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.SignerTokenMappingDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("DocumentCollectionId");

                    b.Property<Guid>("GuidToken");

                    b.Property<string>("JwtToken");

                    b.Property<Guid>("SignerId");

                    b.HasKey("Id");

                    b.ToTable("SignerTokensMapping");
                });

            modelBuilder.Entity("DAL.DAOs.Groups.GroupDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<int>("GroupStatus");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("DAL.DAOs.LogDAO", b =>
                {
                    b.Property<DateTime>("TimeStamp");

                    b.Property<string>("Exception");

                    b.Property<string>("Level");

                    b.Property<string>("Message");

                    b.Property<string>("MessageTemplate");

                    b.HasKey("TimeStamp");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("DAL.DAOs.Programs.ProgramDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("DocumentsPerMonth");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<bool>("OnlineMode");

                    b.Property<bool>("ServerSignature");

                    b.Property<bool>("SmartCard");

                    b.Property<long>("SmsPerMonth");

                    b.Property<long>("TemplatesPerMonth");

                    b.Property<long>("Users");

                    b.HasKey("Id");

                    b.ToTable("Programs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            DocumentsPerMonth = 5L,
                            Name = "Trial",
                            Note = "Upgrade now by calling our Support Center: (+972)3-1111111",
                            OnlineMode = false,
                            ServerSignature = false,
                            SmartCard = false,
                            SmsPerMonth = 0L,
                            TemplatesPerMonth = 2L,
                            Users = 0L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            DocumentsPerMonth = -1L,
                            Name = "Unlimited",
                            OnlineMode = true,
                            ServerSignature = true,
                            SmartCard = true,
                            SmsPerMonth = -1L,
                            TemplatesPerMonth = -1L,
                            Users = -1L
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            DocumentsPerMonth = 50L,
                            Name = "Basic",
                            OnlineMode = true,
                            ServerSignature = true,
                            SmartCard = true,
                            SmsPerMonth = 200L,
                            TemplatesPerMonth = 15L,
                            Users = 2L
                        });
                });

            modelBuilder.Entity("DAL.DAOs.Programs.ProgramUtilizationDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Documents");

                    b.Property<DateTime>("Expired");

                    b.Property<long>("SMS");

                    b.Property<long>("Templates");

                    b.Property<long>("Users");

                    b.HasKey("Id");

                    b.ToTable("ProgramUtilizations");
                });

            modelBuilder.Entity("DAL.DAOs.Templates.TemplateDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid>("GroupId");

                    b.Property<DateTime>("LastUpdatetime");

                    b.Property<string>("Name");

                    b.Property<int>("UsedCount");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("DAL.DAOs.Templates.TemplateSignatureFieldDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("SignaturFieldType");

                    b.Property<Guid>("TemplateId");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateSignatureFields");
                });

            modelBuilder.Entity("DAL.DAOs.Templates.TemplateTextFieldDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Regex");

                    b.Property<Guid>("TemplateId");

                    b.Property<int>("TextFieldType");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("TemplateTextFields");
                });

            modelBuilder.Entity("DAL.DAOs.Users.UserDAO", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("CompanyId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<string>("Email");

                    b.Property<Guid>("GroupId");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<Guid?>("ProgramUtilizationId");

                    b.Property<int>("Status");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreationTime = new DateTime(2020, 4, 30, 6, 14, 44, 872, DateTimeKind.Utc).AddTicks(6373),
                            Email = "systemadmin@comda.co.il",
                            GroupId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "SystemAdmin",
                            Password = "aFDgUq3rMdhhvRqzQ+/9v51hevUQyVubl2XdsvpZqQ/Q4dVz",
                            Status = 2,
                            Type = 4
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CompanyId = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreationTime = new DateTime(2020, 4, 30, 6, 14, 44, 872, DateTimeKind.Utc).AddTicks(8294),
                            Email = "paymentAdmin@comda.co.il",
                            GroupId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Name = "PaymentAdmin",
                            Password = "aFDgUq3rMdhhvRqzQ+/9v51hevUQyVubl2XdsvpZqQ/Q4dVz",
                            Status = 2,
                            Type = 4
                        });
                });

            modelBuilder.Entity("DAL.DAOs.Users.UserTokensDAO", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<string>("RefreshToken");

                    b.Property<DateTime>("RefreshTokenExpiredTime");

                    b.Property<string>("ResetPasswordToken");

                    b.HasKey("UserId");

                    b.ToTable("UsersTokens");
                });

            modelBuilder.Entity("DAL.DAOs.Companies.CompanyConfigurationDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Companies.CompanyDAO", "Company")
                        .WithOne("CompanyConfiguration")
                        .HasForeignKey("DAL.DAOs.Companies.CompanyConfigurationDAO", "CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Companies.CompanyDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Programs.ProgramDAO", "Program")
                        .WithMany("Companies")
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.CompanyMessageDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Companies.CompanyConfigurationDAO", "CompanyConfiguration")
                        .WithMany("CompanyMessages")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.MessageProviderDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Companies.CompanyConfigurationDAO", "CompanyConfiguration")
                        .WithMany("MessageProviders")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Configurations.UserConfigurationDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Users.UserDAO", "User")
                        .WithOne("UserConfiguration")
                        .HasForeignKey("DAL.DAOs.Configurations.UserConfigurationDAO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Contacts.ContactDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Users.UserDAO", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Contacts.ContactSealsDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Contacts.ContactDAO", "Contact")
                        .WithMany("Seals")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.DocumentCollectionDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Users.UserDAO", "User")
                        .WithMany("DocumentCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.DocumentDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Documents.DocumentCollectionDAO", "DocumentCollection")
                        .WithMany("Documents")
                        .HasForeignKey("DocumentCollectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.DAOs.Templates.TemplateDAO", "Template")
                        .WithMany("Documents")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.SignerFieldDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Documents.Signers.SignerDAO", "Signer")
                        .WithMany("SignerFields")
                        .HasForeignKey("SignerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.NotesDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Documents.Signers.SignerDAO", "Signer")
                        .WithOne("Notes")
                        .HasForeignKey("DAL.DAOs.Documents.Signers.NotesDAO", "SignerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.SignerAttachmentDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Documents.Signers.SignerDAO", "Signer")
                        .WithMany("SignerAttachments")
                        .HasForeignKey("SignerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Documents.Signers.SignerDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Contacts.ContactDAO", "Contact")
                        .WithMany("Signers")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DAL.DAOs.Documents.DocumentCollectionDAO", "DocumentCollection")
                        .WithMany("Signers")
                        .HasForeignKey("DocumentCollectionId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("DAL.DAOs.Groups.GroupDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Companies.CompanyDAO", "Company")
                        .WithMany("Groups")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Templates.TemplateSignatureFieldDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Templates.TemplateDAO", "Template")
                        .WithMany("TemplateSignatureFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Templates.TemplateTextFieldDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Templates.TemplateDAO", "Template")
                        .WithMany("TemplateTextFields")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Users.UserDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Companies.CompanyDAO", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.DAOs.Users.UserTokensDAO", b =>
                {
                    b.HasOne("DAL.DAOs.Users.UserDAO", "User")
                        .WithOne("UserTokens")
                        .HasForeignKey("DAL.DAOs.Users.UserTokensDAO", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
